### ISSUE TITLE
unnecessary(?) implementation of get/setcontext on arm breaks armhf

### ISSUE THREAD

**Issue by jannic** [zedshaw/mongrel2#232]
On armhf, the test suite fails with the following error message:
````
sh ./tests/runtests.sh
Running unit tests:
Segmentation fault
ERROR in test tests/bstr_tests:
make[1]: *** [tests] Error 1
````
This is caused by the implementation of getcontext/setcontext embedded in src/task/. It's just not compatible with armhf. And it seems unnecessary even on armel, because by now these functions are implemented by the libc.
(But I only verified that on debian - not sure about other linux distributions.)
If it's true that all (relevant) linux distributions do implement these functions, I can provide a patch to disable the embedded version.

**Comment by jasom** [comment]
Fixed by #253
