### ISSUE TITLE
Upgrade PolarSSL because of vulnerabilities

### ISSUE THREAD

**Issue by winks** [zedshaw/mongrel2#244]
https://www.certifiedsecure.com/polarssl-advisory/

**Comment by jasom** [comment]
Oh, look a bug in ASN.1 parsing code.  How not surprising...

I'll work on a hotfix tonight.

**Comment by winks** [comment]
:+1: 

Sorry that I'm just throwing it over the wall like this but I don't actively use m2 right now and my motivation to c is also a bit low atm :)

**Comment by Funi1234** [comment]
@jasom has this been fixed?

**Comment by aidenkeating** [comment]
I have added a pull request for this #250
