### ISSUE TITLE
Build brakes because tests/ca/m2-cert.pem expired

### ISSUE THREAD

**Issue by artemharutyunyan** [zedshaw/mongrel2#251]
$ openssl x509 -in certs/m2-cert.pem -noout -dates -subject
notBefore=Mar 13 05:57:52 2014 GMT
notAfter=Mar 13 05:57:52 2015 GMT
subject= /C=AU/ST=Some-State/O=Internet Widgits Pty Ltd/CN=example.com

Looks like you've hit the same problem a year ago, so probably it makes sense to generate test certificates with a longer lifetime.

**Comment by jasom** [comment]
Fixed by #245
