### ISSUE TITLE
use undefined variables.

### ISSUE THREAD

**Issue by holmescn** [zedshaw/mongrel2#263]
When I compile mongrel2 without the -DNDEBUG option, it fails because `src/connection.c:1040`

    int Connection_deliver_raw_internal(Connection *conn, tns_value_t *data)
    {
        bstring buf;
        check(data->type==tns_tag_string, "deliver_raw_internal expected a string.");
        buf=data->value.string;
        int ret= IOBuf_send_all(conn->iob, bdata(buf), blength(buf));
        check_debug(ret==blength(buf), "Failed to send all of the data: %d of %d", rc, avail) // this line.
        return 0;

    error:
        return -1;
    }

It is obviously that the variable `rc` and `avail` are undefined. I don't known how to define them. So I disable them to get passed.

**Comment by jasom** [comment]
That is really embarassing.
